
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.3
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: MySQL
          MYSQL_USER: root
          MYSQL_PASSWORD: 
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      # - run:
      #     command: |
      #       for i in `seq 1 10`;
      #       do
      #         nc -z 127.0.0.1 3306 && echo Success && exit 0
      #         echo -n .
      #         sleep 1
      #       done
      #       echo Failed waiting for MySQL && exit 1
      # - run:
      #     name: Install MySQL CLI; Import dummy data; run an example query
      #     command: |
      #       sudo apt-get install default-mysql-client
      #       mysql -h 127.0.0.1 -u root -Kmvanesa@22 MySQL
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app