
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.3
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ROOT_PASSWORD: 0072707
          MYSQL_DATABASE: my_database
          MYSQL_USER: root
          MYSQL_PASSWORD: 0072707
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app


