# Generated by Django 3.0.6 on 2020-06-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200603_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
