# Generated by Django 3.0.6 on 2020-06-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200603_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
